import axios from "axios";
import Head from "next/head";
import { useEffect } from "react";
import Tree from "../components/Tree";
import styles from "../styles/Home.module.css";

export default function Home({ treeData, articles }) {
  useEffect(() => {
    localStorage.setItem("collection", JSON.stringify(articles.collection));
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>WaySeven Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Tree treeData={treeData} />
    </div>
  );
}

export async function getServerSideProps(ctx) {
  const { data } = await axios.get("http://localhost:3000/api/collections");
  const { data: articles } = await axios.get(
    "http://localhost:3000/api/articles"
  );

  return {
    props: {
      treeData: data.jsonData,
      articles: articles,
    },
  };
}
